name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        java: ['17']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'liberica'
    - name: Debug
      shell: bash
      run: |
        echo "PATH: $PATH"
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          echo "MSSDK_HOME"
          ls -la /c/Program\ Files\ \(x86\)/Windows\ Kits/*/Lib/
#          echo "MINGW32"
#          ls -la /mingw32/
          echo "MSYS64"
          ls -la /msys64/
        else
          which -a pkg-config
        fi
    - name: Build with Ant
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          export MINGW64_PATH=/mingw64
#          export MINGW32_PATH=/mingw32
#          export PATH=$MINGW64_PATH/bin/:$MINGW32_PATH/bin/:/msys64/usr/bin/:$PATH
          export PATH=/msys64/usr/bin/:$PATH
          export MSSDK_HOME=/c/Program\ Files\ \(x86\)/Windows\ Kits/10/Lib/10.0.22621.0

          choco install ant
          pacman --noconfirm --disable-download-timeout -S pactoys
          pacboy --noconfirm --disable-download-timeout -S lcms2:m libraw:m lensfun:m ntldd-git:m pkg-config:m
        
          MINGW_DIR=$MINGW64_PATH ant -f windows/build.xml -lib lightcrafts/lib zip
          ant -f windows/build.xml clean-native
#          TARGET_ARCH=i686 MINGW_DIR=$MINGW32_PATH ant -f windows/build.xml -Dno-ivy=true -lib lightcrafts zip
        else
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
          brew install ant lensfun libjpeg-turbo libomp libraw libtiff libxml2 little-cms2 rsync
#          brew install --build-from-source lensfun
          ant -f macosx/build.xml zip
        fi
#    - name: Upload Artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: LightZone-${{ matrix.os }}
#        path: |
#          windows/LightZone-windows*.zip
#          macosx/LightZone-macosx*.zip