name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, macos-14]
        java: ['17']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'liberica'
    - name: Install MSYS2 on Windows
      if: startsWith(matrix.os, 'windows')
      uses: msys2/setup-msys2@v2
      with:
        update: true
        pacboy: lcms2:m libraw:m lensfun:m ntldd-git:m pkgconf:m
    - name: Build on Windows
      if: startsWith(matrix.os, 'windows')
      shell: bash
      run: |
        export PATH=/msys64/usr/bin/:/msys32/usr/bin/:$PATH
        export MSSDK_HOME=/c/Program\ Files\ \(x86\)/Windows\ Kits/10/Lib/10.0.22621.0
        gradle windows:jpackage
        # MSYSTEM=MINGW32 TARGET_ARCH=i686 gradle windows:jpackage
    - name: Build on macOS
      if: startsWith(matrix.os, 'macos')
      run: |
        export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
        brew install gradle lcms2 lensfun libjpeg-turbo libomp libraw libtiff
        if [ "${{ matrix.os }}" == "macos-14" ]; then
          export LIBOMP_PATH=/opt/homebrew/opt/libomp
          TARGET_ARCH=arm64 gradle macos:jpackage
        else
          gradle macos:jpackage
        fi
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LightZone-${{ matrix.os }}
        path: |
          windows/build/jpackage/LightZone-Installer*.exe
          macosx/build/jpackage/LightZone-Installer*.dmg
